[project]
name = "flask-htmx-spike"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "authlib>=1.5.1",
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "requests>=2.32.3",
]
